#!/bin/bash

mode=$(xrandr | grep -m 1 "connected primary" | awk '{ print $4 }' | cut -f1 -d "+")
monitor=$(xrandr | grep -m 1 "connected primary" | awk '{ print $1 }')
xrandr --output $monitor --mode $mode