#!/bin/bash

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install -y flathub com.usebottles.bottles
flatpak install -y flathub com.bitwarden.desktop
flatpak install -y flathub com.getpostman.Postman
flatpak install -y flathub com.discordapp.Discord

rm "${0}"
