#!/bin/bash

#flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo > /dev/null & 
#flatpak install -y flathub com.usebottles.bottles > /dev/null & 
#flatpak install -y flathub com.bitwarden.desktop > /dev/null &
#flatpak install -y flathub com.getpostman.Postman > /dev/null &
#flatpak install -y flathub com.discordapp.Discord > /dev/null &
#
#rm "${0}"
