#!/bin/bash

echo password | sudo -S systemctl start configure-sources-list.service
echo password | sudo -S systemctl enable configure-sources-list.service

echo password | sudo -S systemctl start install-flatpak-apps.service
echo password | sudo -S systemctl enable install-flatpak-apps.service

echo password | sudo -S systemctl start install-virtualbox.service
echo password | sudo -S systemctl enable install-virtualbox.service

echo password | sudo -S systemctl start install-drivers.service
echo password | sudo -S systemctl enable install-drivers.service

echo password | sudo -S systemctl start install-kyocera-driver.service
echo password | sudo -S systemctl enable install-kyocera-driver.service

echo password | sudo -S rm -f /etc/X11/Xsession.d/91start-system-adjustment-services
echo password | sudo -S rm -f /etc/X11/Xsession.d/90set-theme