#!/bin/sh

set -e

lb config noauto \
          --debian-installer live \
          --debian-installer-distribution bookworm \
          --debian-installer-gui true \
	  --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
          --archive-areas "main contrib non-free non-free-firmware" \
          --iso-volume ugrach \
          --clean \
          --color \
          --image-name ugrach.beta \
	  --linux-packages "linux-image linux-headers"

"${@}"
