#!/bin/sh

set -e

lb config noauto \
	  --apt-recommends true \
	  --apt-indices true \
	  --architectures amd64 \
          --archive-areas "main contrib non-free non-free-firmware" \
	  --binary-images iso-hybrid \
	  --binary-filesystem fat32 \
          --clean \
          --color \
          --debian-installer live \
          --debian-installer-distribution bookworm \
          --debian-installer-gui true \
	  --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
	  --distribution bookworm \
	  --firmware-binary true \
	  --firmware-chroot true \
	  --security true \
          --iso-volume ugrach \
          --image-name ugrach.beta \
	  --linux-packages "linux-image linux-headers"

"${@}"
